---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-api-cisco-com-v1alpha1-ciscoaciaim
  failurePolicy: Fail
  name: mciscoaciaim.kb.io
  rules:
  - apiGroups:
    - api.cisco.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ciscoaciaims
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-api-cisco-com-v1alpha1-ciscoaciaim
  failurePolicy: Fail
  name: vciscoaciaim.kb.io
  rules:
  - apiGroups:
    - api.cisco.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ciscoaciaims
  sideEffects: None
