# permissions for end users to edit ciscoaciaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aim-operator
    app.kubernetes.io/managed-by: kustomize
  name: ciscoaciaim-editor-role
rules:
- apiGroups:
  - api.cisco.com
  resources:
  - ciscoaciaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cisco.com
  resources:
  - ciscoaciaims/status
  verbs:
  - get
