---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.cisco.com
  resources:
  - ciscoaciaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cisco.com
  resources:
  - ciscoaciaims/finalizers
  verbs:
  - update
- apiGroups:
  - api.cisco.com
  resources:
  - ciscoaciaims/status
  verbs:
  - get
  - patch
  - update
